const guides={pechi:{name:'ふわペチ',hello:'むずかしく考えなくて大丈夫。一緒にひとつずつ見るだふわ！',line:'まずは、小さなひと工夫からだふわ。'},kuro:{name:'クロ',hello:'確認させてくれ。知っておけば、安心して使えるコツがある。',line:'しくみを知ると、確認するポイントが見えてくる。'},kuromi:{name:'クロミ姐さん',hello:'便利に使うために、守るコツも覚えていくわよ。',line:'大切な情報は、あなたが守ってあげるのよ。'}};
const lessons=[
{id:'input',tag:'みんなにおすすめ',title:'この情報、AIに入れていい？',sub:'名前や秘密は、ひと呼吸。',text:'名前・住所・電話番号、お客さまの情報、まだ公開していない仕事の資料。こうした情報は、そのままAIに渡さないようにしよう。',example:'そのまま：山田花子さんの電話番号と相談内容をまとめて。\n工夫した例：お客さまAの相談を、個人がわからない内容だけでまとめて。',action:'送信前に、名前・連絡先・秘密が入っていないか確認する。不要な情報は削って、一般的な例に置き換えよう。',more:'名前だけを「Aさん」に変えても、住所・日時・出来事の組み合わせで、その人がわかることがあります。ファイルや画像に含まれる情報も確認しよう。仕事の資料は会社が認めたサービスとルールに従ってね。',q:'お客さまの相談をまとめたい。最初にすることは？',choices:['全文をそのまま送る','個人がわかる情報と秘密を取り除く'],correct:1,feedback:'名前だけでなく、連絡先や細かな出来事にも目を向けよう。'},
{id:'setting',tag:'みんなにおすすめ',title:'会話は、どう使われるの？',sub:'設定を見るのも、あんしんの一歩。',text:'AIとの会話が、AIをよくするために使われることがあります。扱いはサービス・契約・設定によって違うので、使う前に確認しよう。',example:'設定画面で「データ」「プライバシー」「モデルの改善」などの項目を探す。わからない言葉は、そのサービスの公式ヘルプで確認する。',action:'今使っているAIの設定を開き、会話が改善に使われるか確認する。必要に応じて利用設定を変更しよう。',more:'「改善に使わない」「履歴に残さない」「一定期間後に削除する」は、それぞれ別の話です。一時チャットでも、保存や確認のために扱われる場合があります。評価ボタンから送る会話の扱いも、サービスごとに確認しよう。設定を変えても、秘密を何でも送ってよいわけではありません。',q:'「AIの改善に使わない」にしたら、社外秘の資料を自由に送っていい？',choices:['会社のルールと情報の扱いを、別に確認する','もう何でも送って大丈夫'],correct:0,feedback:'設定は大事。でも、送る情報を選ぶことも同じくらい大事だよ。'},
{id:'permission',tag:'AIに操作を頼む人へ',title:'AIに、どこまでおまかせする？',sub:'お願いする範囲は、小さく。',text:'ファイルの整理や操作をするAIには、必要な場所だけを使わせよう。パソコンの中すべてを任せるより、練習用のフォルダから始めると確認しやすいよ。',example:'「この練習フォルダだけ見て、整理案を出して。削除や送信は、確認してからにしてね。」',action:'任せる場所と作業を決める。削除・送信・購入などは、実行前に内容を確認しよう。',more:'AIが何をしたか、操作の記録も確認します。大事なファイルは先にコピーしておこう。設定で使える範囲を制限できるなら活用してね。お願いの文章だけで、すべての操作を防げるとは限りません。',q:'AIにファイル整理を頼むなら？',choices:['練習フォルダで、変更内容を確認する','パソコン全部を、確認なしで任せる'],correct:0,feedback:'小さく試して、結果を見る。これが安心して任せるコツ。'},
{id:'package',tag:'アプリを作る人へ',title:'「これを入れて」と言われたら？',sub:'追加する前に、出どころを見る。',text:'AIがすすめる追加プログラムには、名前の間違いや、危険なものが混ざることがあります。知らないものを、そのまま入れないようにしよう。',example:'AIが出したインストール命令をすぐに実行せず、公式の説明と名前・配布元を見比べる。',action:'追加する前に、公式の配布元を確認。わからないときは、詳しい人に命令の内容を見てもらおう。',more:'追加プログラムのまとまりを「パッケージ」と呼びます。Aikido Safe Chainなど、安全確認を助ける道具もありますが、危険をすべて防ぐ保証はありません。導入するときも、公式の案内を確認しよう。',q:'AIが教えた追加プログラム。どうする？',choices:['AIが言うならすぐ入れる','公式の配布元と内容を確認する'],correct:1,feedback:'それらしい名前でも、公式のものか確かめよう。'},
{id:'key',tag:'アプリを作る人へ',title:'AIの「合いかぎ」を守ろう。',sub:'APIキーは、秘密のままに。',text:'アプリからAIを使うための秘密の文字列を「APIキー」といいます。他の人に知られると、勝手に使われて料金がかかることがあります。',example:'APIキーを、公開するプログラム・画面の写真・共有チャットに載せない。公開するウェブ画面の中にも入れない。',action:'APIキーは、サーバー側の秘密を保管する設定で管理する。もし公開してしまったら、すぐ無効にして新しいキーを作り、利用履歴を確認しよう。',more:'開発では環境変数やSecretなどを使います。.envというファイルを使う場合も、Gitなどの共有対象から外します。ただし、ウェブ画面へ組み込んだキーは隠せません。GitHubの漏えい検知も補助に使い、公開前に確認しよう。',q:'APIキーが写った画像を公開してしまった！',choices:['画像を消して、それで終わり','キーを無効にし、利用履歴も確認する'],correct:1,feedback:'一度見られたキーは、画像を消しても使われる可能性があるよ。'}];
let selected='pechi';const done=new Set();const $=s=>document.querySelector(s);const dialog=$('#lesson');let active=null;
function setGuide(key){selected=key;document.querySelectorAll('[data-guide]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.guide===key)));$('#greeting').replaceChildren();const n=document.createElement('strong');n.textContent=guides[key].name;$('#greeting').append(n,document.createTextNode(guides[key].hello));}
document.querySelectorAll('[data-guide]').forEach(b=>b.addEventListener('click',()=>setGuide(b.dataset.guide)));
function render(){const root=$('#cards');root.replaceChildren();lessons.forEach((l,i)=>{const b=document.createElement('button');b.className='card'+(done.has(l.id)?' done':'');b.style.setProperty('--accent',['#ffcc64','#58c6c2','#ef90b0'][i%3]);b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')} · ${l.tag}</span><h3>${l.title}</h3><p>${l.sub}</p><span class="read">${done.has(l.id)?'✓ 読んだよ':'ひらいてみる'}<span aria-hidden="true">↗</span></span>`;b.onclick=()=>openLesson(l);root.append(b)})}
function openLesson(l){active=l;$('#lessonLabel').textContent=l.tag;$('#dialogTitle').textContent=l.title;$('#mentorImage').src=`assets/${selected}.png`;$('#mentorImage').alt=guides[selected].name;$('#mentorLine').textContent=guides[selected].line;$('#explanation').textContent=l.text;$('#example').textContent=l.example;$('#action').textContent=l.action;$('#more').textContent=l.more;$('#question').textContent=l.q;$('#feedback').textContent='';$('#answers').replaceChildren();dialog.querySelectorAll('details').forEach(d=>d.open=false);l.choices.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c;b.onclick=()=>{document.querySelectorAll('#answers button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#feedback').textContent=(i===l.correct?'そのとおり！ ':'もう一度考えてみよう。 ')+l.feedback};$('#answers').append(b)});dialog.showModal();dialog.scrollTop=0;}
$('#close').onclick=()=>dialog.close();$('#finish').onclick=()=>{done.add(active.id);dialog.close();render()};dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});setGuide('pechi');render();
