const guides={pechi:{name:'ふわペチ',hello:'むずかしく考えなくて大丈夫。一緒にひとつずつ見るだふわ！',line:'まずは、小さなひと工夫からだふわ。'},kuro:{name:'クロ',hello:'確認させてくれ。知っておけば、安心して使えるコツがある。',line:'しくみを知ると、確認するポイントが見えてくる。'},kuromi:{name:'クロミ姐さん',hello:'便利に使うために、守るコツも覚えていくわよ。',line:'大切な情報は、あなたが守ってあげるのよ。'}};
const lessons=[
{id:'input',tag:'すべての利用者へ',title:'この情報、AIに入れていい？',sub:'名前や秘密は、ひと呼吸。',text:'名前・住所・電話番号、お客さまの情報、まだ公開していない仕事の資料。こうした情報は、そのままAIに渡さないようにしましょう。',example:'そのまま：山田花子さんの電話番号と相談内容をまとめて。\n工夫した例：お客さまAの相談を、個人がわからない内容だけでまとめて。',action:'送信前に、名前・連絡先・秘密が入っていないか確認する。不要な情報は削って、一般的な例に置き換えよう。',more:'名前だけを「Aさん」に変えても、住所・日時・出来事の組み合わせで、その人がわかることがあります。ファイルや画像に含まれる情報も確認しましょう。仕事の資料は会社が認めたサービスとルールに従ってください。',q:'お客さまの相談をまとめたい。最初にすることは？',choices:['全文をそのまま送る','個人がわかる情報と秘密を取り除く'],correct:1,feedback:'名前だけでなく、連絡先や細かな出来事にも確認しましょう。'},
{id:'setting',tag:'すべての利用者へ',title:'会話を学習に使わせない設定は？',sub:'サービスごとの確認場所を押さえる。',text:'会話がAIの学習や改善に使われるかは、サービス・契約・設定によって異なります。個人向けのアカウントでは、次の場所で設定を確認できます。',example:'ChatGPT：アカウントメニュー → 設定 → データコントロール →「すべての人のためにモデルを改善する（Improve the model for everyone）」をオフ。\n\nGemini：設定とヘルプ → アクティビティ →「アクティビティの保存」の「オン」を選び、「オフにする」を選択。\n\nClaude：アカウントの名前 → 設定 → プライバシー →「AIモデルの改善に協力する（Help Improve our AI models）」をオフ。',action:'利用中のアカウントで設定を開き、学習・改善への利用がオフになっていることを確認してください。表示名や場所は、端末・言語・契約によって異なる場合があります。',more:'ここでいう学習は、会話をAIモデルの改善に利用することです。履歴の保存や、あなたの情報を覚えるメモリとは別の設定です。\n\nChatGPT：オフにしても履歴は残ります。回答の評価などでフィードバックを送ると、関連する会話が学習に使われる場合があります。\n\nGemini：オフでも、サービス提供やフィードバック処理のため、会話が最長72時間保存されます。仕事・学校用アカウントは管理者が設定を管理する場合があります。\n\nClaude：オフにすると、以後の新しい会話などは今後のモデル学習に使われません。ただし、安全対策のための利用など、例外があります。\n\nどのサービスでも、学習利用をオフにすれば秘密を自由に入力できる、という意味ではありません。仕事では会社のルールを優先してください。',q:'学習・改善への利用をオフにすれば、社外秘の資料を自由に送れますか？',choices:['会社のルールと情報の扱いを、別に確認する','どんな情報でも送ってよい'],correct:0,feedback:'設定の確認に加えて、入力する情報を選ぶことも必要です。'},
{id:'permission',tag:'AIに操作を頼む人へ',title:'AIに、どこまでおまかせする？',sub:'お願いする範囲は、小さく。',text:'ファイルの整理や操作をするAIには、必要な場所だけを使わせよう。パソコンの中すべてを任せるより、練習用のフォルダから始めると確認しやすくなります。',example:'「この練習フォルダだけ見て、整理案を出して。削除や送信は、確認してからにしてね。」',action:'任せる場所と作業を決める。削除・送信・購入などは、実行前に内容を確認しましょう。',more:'AIが何をしたか、操作の記録も確認します。大事なファイルは先にコピーしておきましょう。設定で使える範囲を制限できるなら活用してください。お願いの文章だけで、すべての操作を防げるとは限りません。',q:'AIにファイル整理を頼むなら？',choices:['練習フォルダで、変更内容を確認する','パソコン全部を、確認なしで任せる'],correct:0,feedback:'小さく試して、結果を見る。これが安心して任せる基本です。'},
{id:'package',tag:'アプリを作る人へ',title:'「これを入れて」と言われたら？',sub:'追加する前に、出どころを見る。',text:'AIがすすめる追加プログラムには、名前の間違いや、危険なものが混ざることがあります。知らないものを、そのまま入れないようにしましょう。',example:'AIが出したインストール命令をすぐに実行せず、公式の説明と名前・配布元を見比べる。',action:'追加する前に、公式の配布元を確認。わからないときは、詳しい人に命令の内容を確認してもらいましょう。',more:'追加プログラムのまとまりを「パッケージ」と呼びます。Aikido Safe Chainなど、安全確認を助ける道具もありますが、危険をすべて防ぐ保証はありません。導入するときも、公式の案内を確認しましょう。',q:'AIが教えた追加プログラム。どうする？',choices:['AIが言うならすぐ入れる','公式の配布元と内容を確認する'],correct:1,feedback:'それらしい名前でも、公式のものか確かめよう。'},
{id:'key',tag:'アプリを作る人へ',title:'APIキーとは？ なぜ秘密にする？',sub:'あなたの利用権限と料金に関わる情報。',text:'APIとは、アプリやプログラムからAIなどのサービスを利用するための窓口です。APIキーは、その利用者を確認し、利用を許可するための秘密の文字列です。アプリがAIに文章の作成などを依頼するときに使います。パスワードに近い、大切な認証情報です。',example:'自作アプリ → APIキーで利用を認証 → AIサービスに依頼 → 回答が返る。\n\nAPIキーが漏れると、他人があなたの契約でAIを大量に利用し、多額の請求がくることがあります。キーの権限によっては、データの不正な利用につながる場合もあります。',action:'APIキーを公開コード、画面の写真、共有チャットに載せないでください。漏えいした場合は、すぐにキーを無効にして再発行し、利用履歴・請求状況を確認してください。必要に応じてサービスのサポートにも連絡します。',more:'通常のAIチャット画面を使うだけなら、自分でAPIキーを用意する必要はありません。アプリ開発や外部ツールとの接続で必要になることがあります。チャットの月額契約とAPIの料金は別になっているサービスもあるため、利用前に確認してください。\n\n開発では、サーバー側の環境変数やSecret（秘密情報の保管設定）で管理します。.envファイルを使う場合も、Gitなどで共有しないようにします。ウェブ画面のプログラムに組み込むと、利用者から見えてしまうため、隠したつもりでも安全ではありません。\n\n利用上限や通知を設定し、必要な権限だけに絞ることも対策です。ただし、予算の通知が必ず利用を停止するとは限りません。漏えい時は、投稿や画像を削除するだけでは不十分です。',q:'APIキーが写った画像を公開してしまった場合は？',choices:['画像を削除すれば対応は終わり','キーを無効にし、利用履歴・請求状況も確認する'],correct:1,feedback:'一度漏れたキーは、画像を削除しても悪用される可能性があります。'}];
let selected='pechi';const done=new Set();const $=s=>document.querySelector(s);const dialog=$('#lesson');let active=null;
function setGuide(key){selected=key;document.querySelectorAll('[data-guide]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.guide===key)));$('#greeting').replaceChildren();const n=document.createElement('strong');n.textContent=guides[key].name;$('#greeting').append(n,document.createTextNode(guides[key].hello));}
document.querySelectorAll('[data-guide]').forEach(b=>b.addEventListener('click',()=>setGuide(b.dataset.guide)));
function render(){const root=$('#cards');root.replaceChildren();lessons.forEach((l,i)=>{const b=document.createElement('button');b.className='card'+(done.has(l.id)?' done':'');b.style.setProperty('--accent',['#ffcc64','#58c6c2','#ef90b0'][i%3]);b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')} · ${l.tag}</span><h3>${l.title}</h3><p>${l.sub}</p><span class="read">${done.has(l.id)?'✓ 確認済み':'詳しく読む'}<span aria-hidden="true">↗</span></span>`;b.onclick=()=>openLesson(l);root.append(b)})}
function openLesson(l){active=l;$('#lessonLabel').textContent=l.tag;$('#dialogTitle').textContent=l.title;$('#mentorImage').src=`assets/${selected}.png`;$('#mentorImage').alt=guides[selected].name;$('#mentorLine').textContent=guides[selected].line;$('#explanation').textContent=l.text;$('#example').textContent=l.example;$('#action').textContent=l.action;$('#more').textContent=l.more;$('#question').textContent=l.q;$('#feedback').textContent='';$('#answers').replaceChildren();dialog.querySelectorAll('details').forEach(d=>d.open=false);l.choices.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c;b.onclick=()=>{document.querySelectorAll('#answers button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#feedback').textContent=(i===l.correct?'正解です。 ':'ポイントを確認しましょう。 ')+l.feedback};$('#answers').append(b)});dialog.showModal();dialog.scrollTop=0;}
$('#close').onclick=()=>dialog.close();$('#finish').onclick=()=>{done.add(active.id);dialog.close();render()};dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});setGuide('pechi');render();
