const navigators={pechi:{name:'ふわペチ',role:'やさしく寄り添う',image:'./assets/pechi.png',hello:'いっしょに、気になることから見てみるだふわ！',line:'大丈夫。ポイントだけ、いっしょに見るだふわ！'},kuromi:{name:'クロミ姐さん',role:'ズバッと本質を見抜く',image:'./assets/kuromi.png',hello:'あたしと一緒なら、AIの口車も見抜けるのよ💋',line:'ここが大事よ。AIの言葉、鵜呑みにしちゃダメなのよ💋'},kuro:{name:'エンジニアクロ',role:'仕組みから冷静に案内',image:'./assets/kuro.png',hello:'確認させてくれ。俺がエスコートするよ。',line:'確認させてくれ。仕組みを知れば、判断は難しくない。'}};
const cards=[
{id:'lie',q:'AIって、嘘をつくの？',a:'AIは「知っていることを答える」のではなく、文脈に合いそうな言葉を組み立てます。そのため、もっともらしい間違いを自信ありげに返すことがあります。',tip:'人名・数字・日付・出典は、元の資料や信頼できる別の情報で確認しよう。',purpose:['初心者','調べもの'],scene:['調べる'],route:'🏭 工場で仕組みを見る'},
{id:'memory',q:'前に話したこと、ずっと覚えてる？',a:'同じ会話の中では文脈を参照できますが、別の会話や長い期間をまたいで、何でも正確に覚えているわけではありません。設定やサービスによっても違います。',tip:'大事な前提は「前にも言った」ではなく、その都度短く書き添えよう。',purpose:['初心者','話し相手'],scene:['相談する'],route:'🧪 実験室で試す'},
{id:'private',q:'個人情報を入れても平気？',a:'入力内容の扱いはサービスや設定で異なります。氏名、住所、顧客情報、社外秘などは、入力前に本当に必要かを考えるのが基本です。',tip:'実名や会社名は「Aさん」「B社」に置き換え、必要最小限だけ伝えよう。',purpose:['仕事','経営者'],scene:['資料を扱う'],route:'チェックリストを見る'},
{id:'search',q:'AIの検索結果なら安心？',a:'AI検索は便利ですが、情報源の質や更新日、広告・最適化の影響まで自動で保証するものではありません。「AIが選んだ」こと自体は品質の証明になりません。',tip:'おすすめを見たら、理由・出典・更新日・別の選択肢を確認しよう。',purpose:['調べもの','経営者'],scene:['調べる','買い物'],route:'🏭 工場で仕組みを見る'},
{id:'health',q:'体調の相談、AIだけで決めていい？',a:'AIは一般的な整理には役立ちますが、診断はできません。緊急性の判断や個別の治療は、医療機関や専門家の確認が必要です。',tip:'症状・期間・服薬を整理する補助に使い、受診の代わりにはしない。',purpose:['話し相手'],scene:['健康・お金'],route:'相談先の目安を見る'},
{id:'money',q:'投資や保険の答えを信じていい？',a:'お金の判断は、あなたの状況や制度、最新情報で結論が変わります。AIの回答は一般論や検討材料として扱い、最終判断を任せないことが大切です。',tip:'前提条件と損をする可能性を聞き、公式情報や専門家にも確認しよう。',purpose:['経営者'],scene:['健康・お金'],route:'確認ポイントを見る'},
{id:'tone',q:'自信満々なら、正しいの？',a:'文章の言い切り方と正確さは別物です。AIは不確かな内容でも、自然で断定的な文章を作れます。',tip:'「確実な点・不確かな点・確認方法を分けて」と頼んでみよう。',purpose:['初心者','調べもの'],scene:['調べる'],route:'🧪 実験室で試す'},
{id:'image',q:'AI画像は、本物に見えたら本物？',a:'生成画像や加工画像は、見た目だけでは判別しづらくなっています。画像単体ではなく、投稿元や撮影時期、他の報道も合わせて見る必要があります。',tip:'画像検索や公式発表を使い、「誰が・いつ・どこで」を確認しよう。',purpose:['初心者','調べもの'],scene:['買い物','調べる'],route:'見分け方を見る'},
{id:'copyright',q:'AIが書いた文章、そのまま使える？',a:'事実誤認、既存表現との類似、権利や利用規約の問題が残ることがあります。AIが作ったから自動的に安全、とは限りません。',tip:'公開前に内容・出典・固有表現を確認し、自分の責任で編集しよう。',purpose:['仕事','経営者'],scene:['資料を扱う'],route:'🧪 実験室で試す'},
{id:'minutes',q:'会議メモを丸ごと入れていい？',a:'議事録には個人情報や未公開情報が混ざりやすいものです。使うサービスのデータ取り扱いと、社内ルールを先に確認しましょう。',tip:'入力前に固有名詞・金額・契約情報を伏せ、公開してよい範囲に絞ろう。',purpose:['仕事'],scene:['資料を扱う'],route:'確認リストを見る'},
{id:'prompt',q:'うまい質問ができないと使えない？',a:'特別な呪文は必要ありません。目的、背景、ほしい形を少しずつ伝え、出力を見ながら修正すれば十分です。',tip:'「何のために」「誰向けに」「どんな形で」の3つから伝えよう。',purpose:['初心者','仕事'],scene:['相談する','資料を扱う'],route:'🧪 実験室で試す'},
{id:'emotion',q:'AIは私の気持ちを分かってる？',a:'共感的な言葉は作れますが、人間のように感情を体験しているわけではありません。話を整理する相手としては役立っても、理解の仕方は人間と異なります。',tip:'気持ちの整理に使いつつ、大切な悩みは信頼できる人にも話そう。',purpose:['話し相手'],scene:['相談する'],route:'使い分けを見る'},
{id:'compare',q:'買い物の「おすすめ1位」は信用できる？',a:'おすすめは、条件の伝え方や参照情報で変わります。あなたの優先順位に合うとは限らず、価格や在庫が古いこともあります。',tip:'予算・用途・譲れない条件を伝え、候補ごとの弱点も出してもらおう。',purpose:['調べもの'],scene:['買い物'],route:'比較のコツを見る'},
{id:'boss',q:'経営判断をAIに任せたら速い？',a:'選択肢の整理や下調べは速くなりますが、現場事情、責任、価値判断までは代わってくれません。決定権と説明責任は人間側に残ります。',tip:'案を3つ出させた後、「見落とし」「反対意見」「撤退条件」も聞こう。',purpose:['経営者','仕事'],scene:['資料を扱う'],route:'判断フレームを見る'},
{id:'bias',q:'AIはいつも中立なの？',a:'AIの答えは、学習データ、設計、質問の仕方などの影響を受けます。一つの見方を「普通」や「正解」のように示すことがあります。',tip:'立場の違う人の見方や、反対の結論になる条件も尋ねてみよう。',purpose:['初心者','仕事'],scene:['相談する','調べる'],route:'視点を増やす'}];
let state={navigator:localStorage.getItem('navigator')||'pechi',mode:'purpose',filter:'すべて',query:'',done:new Set(JSON.parse(localStorage.getItem('doneCards')||'[]'))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function setNavigator(key){state.navigator=key;localStorage.setItem('navigator',key);const n=navigators[key];$('#heroImage').src=n.image;$('#heroImage').alt=n.name;$('#miniAvatar').src=n.image;$('#miniAvatar').alt=n.name;$('#guideName').textContent=n.name;$('#guideLine').textContent=n.hello;renderNavigatorOptions();renderCards();}
function renderNavigatorOptions(){const box=$('#navigatorOptions');box.innerHTML='';Object.entries(navigators).forEach(([key,n])=>{const b=document.createElement('button');b.type='button';b.className='navigator-option'+(key===state.navigator?' active':'');b.innerHTML=`<img src="${n.image}" alt=""><div><strong>${n.name}</strong><span>${n.role}</span></div>`;b.onclick=()=>{$('#navigatorDialog').close();setNavigator(key)};box.appendChild(b)})}
function currentTags(){return state.mode==='purpose'?['すべて','初心者','話し相手','調べもの','仕事','経営者']:['すべて','相談する','調べる','買い物','資料を扱う','健康・お金']}
function renderChips(){const box=$('#chips');box.innerHTML='';currentTags().forEach(tag=>{const b=document.createElement('button');b.className='chip'+(tag===state.filter?' active':'');b.textContent=tag==='すべて'?'✦ すべて':tag;b.onclick=()=>{state.filter=tag;renderChips();renderCards()};box.appendChild(b)})}
function filteredCards(){const q=state.query.trim().toLowerCase();return cards.filter(c=>(state.filter==='すべて'||c[state.mode].includes(state.filter))&&(!q||`${c.q} ${c.a} ${c.tip}`.toLowerCase().includes(q)))}
function renderCards(){const box=$('#cardGrid');box.innerHTML='';const list=filteredCards();$('#resultCount').textContent=list.length;$('#emptyState').hidden=!!list.length;list.forEach((c,i)=>{const node=$('#cardTemplate').content.cloneNode(true);const art=node.querySelector('.qa-card'),front=node.querySelector('.card-front'),back=node.querySelector('.card-back');front.style.setProperty('--card-accent',["#ffcc64","#58c6c2","#e9568a"][i%3]);front.querySelector('.card-meta').textContent=`CARD ${String(i+1).padStart(2,'0')} · ${c.purpose[0]}`;front.querySelector('h3').textContent=c.q;back.querySelector('.character-line').textContent=navigators[state.navigator].line;back.querySelector('h3').textContent=c.q;back.querySelector('.answer').textContent=c.a;back.querySelector('.tip p').textContent=c.tip;const done=back.querySelector('.done-button');done.textContent=state.done.has(c.id)?'✓ クリア済み':'わかった！';done.classList.toggle('done',state.done.has(c.id));back.querySelector('.route-button').textContent=c.route;front.onclick=()=>{front.hidden=true;back.hidden=false;front.setAttribute('aria-expanded','true')};back.querySelector('.card-close').onclick=()=>{back.hidden=true;front.hidden=false;front.setAttribute('aria-expanded','false')};done.onclick=()=>{state.done.add(c.id);localStorage.setItem('doneCards',JSON.stringify([...state.done]));done.textContent='✓ クリア済み';done.classList.add('done');updateProgress()};back.querySelector('.route-button').onclick=()=>{const url=c.route.includes('工場')?'https://ai-factory-app-pi.vercel.app/':c.route.includes('実験室')?'https://ai-text-demo-ruddy.vercel.app/':'';if(url){window.open(url,'_blank','noopener,noreferrer')}else{alert('このカードの追加ガイドは準備中です。')}};box.appendChild(node)});updateProgress()}
function updateProgress(){const n=state.done.size,p=Math.round(n/cards.length*100);$('#scoreNumber').textContent=n;$('#scoreRing').style.setProperty('--score',`${p}%`);$('#progressBar').style.width=`${p}%`;$('#progressText').textContent=n?`${cards.length}枚中 ${n}枚をクリア。あと${cards.length-n}枚です。`:'最初のカードをめくってみよう';const badgeData=[['🌱','はじめの一歩',1],['🔎','見極め上手',5],['🧭','AIナビゲーター',12]];$('#badges').innerHTML=badgeData.map(([icon,name,need])=>`<div class="badge ${n<need?'locked':''}"><b>${icon}</b><strong>${name}</strong><small>${need}枚クリアで獲得</small></div>`).join('')}
function showView(view){$('#learnView').hidden=view!=='learn';$('#progressView').hidden=view!=='progress';$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));scrollTo({top:0,behavior:'smooth'});if(view==='progress')updateProgress()}
$$('.nav-link').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('[data-return-learn]').onclick=()=>showView('learn');$$('.filter-tab').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.filter='すべて';$$('.filter-tab').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)});renderChips();renderCards()});$('#searchInput').oninput=e=>{state.query=e.target.value;renderCards()};$('#avatarButton').onclick=$('#heroCharacter').onclick=()=>$('#navigatorDialog').showModal();
const anamDialog=$('#anamDialog'),anamFrame=$('#anamFrame');$('#anamLauncher').onclick=()=>{if(!anamFrame.src)anamFrame.src='https://lab.anam.ai/share/KP40BRfb-o_gZNUbdhGOY';anamDialog.showModal()};$('#anamClose').onclick=()=>anamDialog.close();anamDialog.addEventListener('click',e=>{if(e.target===anamDialog)anamDialog.close()});
function registerWebMCP(){const mc=document.modelContext;if(!mc?.registerTool)return;const ac=new AbortController();Promise.resolve(mc.registerTool({name:'select_navigator',title:'ナビゲーターを選ぶ',description:'学習を案内するキャラクターを選択します。',inputSchema:{type:'object',properties:{navigator:{type:'string',enum:Object.keys(navigators)}},required:['navigator'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({navigator})=>{if(!navigators[navigator])throw new Error('Unknown navigator');setNavigator(navigator);return{navigator,name:navigators[navigator].name}}},{signal:ac.signal})).catch(()=>{});Promise.resolve(mc.registerTool({name:'open_learning_card',title:'学習カードを開く',description:'質問IDを指定して該当するAIリテラシーカードを表示します。',inputSchema:{type:'object',properties:{cardId:{type:'string'}},required:['cardId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({cardId})=>{const c=cards.find(x=>x.id===cardId);if(!c)throw new Error('Card not found');state.query=c.q;$('#searchInput').value=c.q;showView('learn');renderCards();setTimeout(()=>$('.card-front')?.click(),0);return{id:c.id,question:c.q}}},{signal:ac.signal})).catch(()=>{})}
renderNavigatorOptions();renderChips();setNavigator(state.navigator);updateProgress();registerWebMCP();
